spring.application.name=customerservice
logging.level.org.springframework.web: DEBUG

#H2 DB
#spring.h2.console.enabled = true
#spring.datasource.platform = h2
#spring.datasource.url = jdbc:h2:mem:bills

#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=N7_Banking;encrypt=False;TrustServerCertificate=True;
#spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=N7_Banking;encrypt=False;TrustServerCertificate=True;
#spring.datasource.username= admin
#spring.datasource.password=Test@1234

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username= ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2022Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.open-in-view=false

# Show Hibernate SQL (optional, for debugging queries)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Root level (framework + your app)
logging.level.root=INFO

# Add traceId and spanId to log output
logging.pattern.level=%5p [traceId=%X{traceId}, spanId=%X{spanId}] 
logging.file.name=logs/application.log

# Add traceId & spanId to logs
logging.pattern.level=%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.observations.annotations.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/los-realm
app.cors.allowed-origins=http://localhost:5173