spring.application.name=loanservice
logging.level.org.springframework.web: DEBUG

#H2 DB
#spring.h2.console.enabled = true
#spring.datasource.platform = h2
#spring.datasource.url = jdbc:h2:mem:bills

springdoc.packagesToScan=com.banking.loanservice.controller
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=lending;encrypt=False;TrustServerCertificate=True;
spring.datasource.username= admin
spring.datasource.password=Test@1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2022Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.open-in-view=false
server.port=8082
customer.service.url=http://localhost:8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/los-realm
app.cors.allowed-origins=http://localhost:5173