spring.application.name=productservice
logging.level.org.springframework.web: DEBUG

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=product;encrypt=False;TrustServerCertificate=True;
spring.datasource.username= admin
spring.datasource.password=Test@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2022Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.open-in-view=false
server.port=8082
